import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

await mkdir('../.impeccable/review',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const failures=[];page.on('pageerror',e=>failures.push(e.message));
const requests=[];
const source={title:'Illustrative test source',guest:'Test guest',source_url:'https://example.com/episode',text:'A source passage for browser testing.',start_seconds:65};
let next={message:'Start with **activation**. [S1]',sources:{S1:source},artifact:null,skill:'podcast-qa'};
await page.route('**/api/v1/workspace/chat',async route=>{requests.push(route.request().postDataJSON());await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(next)});});
try{
  await page.goto('http://127.0.0.1:5173');
  await page.getByRole('heading',{name:'A little insight. A better next move.'}).waitFor();
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.getByRole('button',{name:'Send message'}).isDisabled(),true);
  assert.equal(await page.locator('[data-action="mode"]').count(),0);
  await page.getByRole('button',{name:'Write about product-market fit'}).click();
  assert.match(await page.getByLabel('Message Lenny').inputValue(),/Write an essay/);
  await page.getByRole('button',{name:'A simple growth calculator'}).click();
  assert.match(await page.getByLabel('Message Lenny').inputValue(),/interactive HTML/);
  await page.getByRole('button',{name:'Improve activation'}).click();
  assert.match(await page.getByLabel('Message Lenny').inputValue(),/activation/);
  await page.getByRole('button',{name:'Send message'}).click();
  await page.getByText('Start with activation. [S1]').waitFor();
  await page.locator('.sources>summary').click();
  await page.getByRole('link',{name:'Illustrative test source'}).waitFor();
  await page.getByText('View passage',{exact:true}).click();
  await page.getByText('A source passage for browser testing.').waitFor();
  next={message:'Your essay is ready. This is illustrative test content.',sources:{S1:source},artifact:{title:'Make activation your next growth decision',language:'markdown',content:'# Make activation your next growth decision\n\n**Growth starts with a useful first experience.**\n\nThis is illustrative content for testing the workspace, not a generated podcast claim.\n\n## Find the moment that matters\n\nLook at what a new user needs to accomplish before you ask them to come back. A clear first step makes the experience easier to understand. [S1]\n\n- **Choose one outcome.** Define a useful first experience.\n- **Measure the journey.** Find where people get stuck.\n- **Run a small experiment.** Learn before expanding.\n\n## The takeaway\n\nMake one part of the first experience better, then check whether it helps.'}};
  next.skill='ship30-essay';
  await page.getByLabel('Message Lenny').fill('Turn this into an essay.');
  await page.getByRole('button',{name:'Send message'}).click();
  const panel=page.getByRole('complementary',{name:'Artifact viewer'});
  await panel.getByRole('heading',{name:'Make activation your next growth decision'}).waitFor();
  assert.equal('mode' in requests.at(-1),false);assert.equal(requests.at(-1).history.length,2);
  assert.equal(requests.at(-1).history[1].skill,'podcast-qa');
  await page.screenshot({path:'../.impeccable/review/automatic-skills-artifact.png',fullPage:true});
  await panel.getByRole('button',{name:'Source',exact:true}).click();
  assert.equal(await panel.getByRole('button',{name:'Source',exact:true}).evaluate(el=>el===document.activeElement),true);
  assert.match(await panel.locator('pre').textContent(),/# Make activation/);
  const download=page.waitForEvent('download');await panel.getByRole('button',{name:'Download artifact'}).click();
  assert.match((await download).suggestedFilename(),/\.md$/);
  await page.getByRole('button',{name:'Close artifact'}).click();
  await page.reload();
  await page.locator('.history-row>button').first().click();
  await page.getByRole('button',{name:/Make activation your next growth decision/}).click();
  assert.equal(await page.getByRole('button',{name:'Close artifact'}).evaluate(el=>el===document.activeElement),true);
  await panel.getByRole('heading',{name:'Make activation your next growth decision'}).waitFor();
  await page.getByRole('button',{name:'Close artifact'}).click();
  assert.equal(await page.getByRole('button',{name:/Make activation your next growth decision/}).evaluate(el=>el===document.activeElement),true);
  next={message:'A tiny interactive demo.',sources:{},skill:'simple-artifact',artifact:{title:'Counter demo',language:'html',content:'<h1>Counter demo</h1><button onclick="this.textContent=Number(this.textContent)+1">0</button><!--'+ 'x'.repeat(20000)+'--><script>try{parent.document.body.dataset.leaked="true"}catch{document.body.dataset.isolated="true"}</script>'}};
  await page.getByLabel('Message Lenny').fill('Make a small counter.');
  await page.getByRole('button',{name:'Send message'}).click();
  await page.frameLocator('#preview').getByRole('button',{name:'0',exact:true}).click();
  await page.frameLocator('#preview').getByRole('button',{name:'1',exact:true}).waitFor();
  assert.equal('mode' in requests.at(-1),false);
  assert.equal(requests.at(-1).history.at(-1).skill,'ship30-essay');
  assert.match(requests.at(-1).history.at(-1).artifact.content,/# Make activation/);
  assert.equal(requests.at(-1).history.at(-1).content,'Your essay is ready. This is illustrative test content.');
  assert.equal(await page.locator('#preview').getAttribute('sandbox'),'allow-scripts allow-forms');
  assert.equal(await page.evaluate(()=>document.body.dataset.leaked),undefined);
  await page.getByRole('button',{name:'Close artifact'}).click();
  const completeSource=next.artifact.content;
  next={message:'An updated counter.',sources:{},skill:'simple-artifact',artifact:{title:'Counter demo',language:'html',content:'<form id="calculate"><button type="submit">Calculate locally</button></form><output id="result">0</output><script>document.querySelector("form").addEventListener("submit",event=>{event.preventDefault();document.querySelector("output").textContent="5";});</script>'}};
  await page.getByLabel('Message Lenny').fill('Add a reset button.');
  await page.getByRole('button',{name:'Send message'}).click();
  await page.getByText('An updated counter.',{exact:true}).waitFor();
  assert.equal(requests.at(-1).history.at(-1).artifact.content,completeSource);
  assert.ok(requests.at(-1).history.at(-1).artifact.content.length>16000);
  await page.frameLocator('#preview').getByRole('button',{name:'Calculate locally'}).click();
  await page.frameLocator('#preview').locator('output').filter({hasText:'5'}).waitFor();
  assert.match(await page.locator('#preview').getAttribute('srcdoc'),/form-action 'none'/);
  await page.getByRole('button',{name:'Close artifact'}).click();
  await page.getByRole('button',{name:/New conversation/}).click();
  await page.unroute('**/api/v1/workspace/chat');
  await page.route('**/api/v1/workspace/chat',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Test: service unavailable.'})}));
  await page.getByLabel('Message Lenny').fill('Test error handling.');
  await page.getByRole('button',{name:'Send message'}).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').textContent(),/service unavailable/);
  await page.unroute('**/api/v1/workspace/chat');
  await page.route('**/api/v1/workspace/chat',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({message:'Recovered. <img src=x onerror="window.xss=true"><script>window.xss=true</script>',sources:{},artifact:null})}));
  await page.getByRole('button',{name:'Retry',exact:true}).click();
  await page.getByText('Recovered.',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.xss),undefined);
  assert.equal(await page.locator('.message.user').count(),1);
  await page.setViewportSize({width:1280,height:800});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.equal(failures.length,0,failures.join('\n'));
  console.log('PASS: one composer without mode controls, mixed suggestions, skill and artifact history, grounded chat, essay preview/source/download, saved history, HTML interaction/isolation, errors/retry, Markdown sanitization, 1280px overflow. No model calls.');
}finally{await browser.close();}
